version: '3.1' 
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql-dump:/docker-entrypoint-initdb.d
    environment:
        MYSQL_ROOT_PASSWORD: "pw1234"
    ports: 
        - 3306:3306
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      REDIS_USER: default
      REDIS_PASSWORD: MDNcVb924a
      HOST: db 
      MYSQL_USER: root
      PASSWORD: pw1234 
      DATABASE: db
  ai:
    build:
      dockerfile: Dockerfile
      context: "./AI"
    volumes:
      - ./AI:/python-docker
    ports:
      - 5000:5000


